{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "lstm_1", "default": null, "conditions": [], "min_value": 16, "max_value": 128, "step": 16, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_1", "default": 0.05, "conditions": [], "min_value": 0.05, "max_value": 0.45, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "lstm_2", "default": null, "conditions": [], "min_value": 16, "max_value": 64, "step": 8, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "dropout_2", "default": 0.05, "conditions": [], "min_value": 0.05, "max_value": 0.45, "step": 0.1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "dense_units", "default": null, "conditions": [], "min_value": 8, "max_value": 64, "step": 8, "sampling": "linear"}}], "values": {"lstm_1": 80, "dropout_1": 0.15000000000000002, "lstm_2": 24, "dropout_2": 0.05, "dense_units": 16}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\MajaE\\src\\repos\\master_ML\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\MajaE\\src\\repos\\master_ML\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\MajaE\\src\\repos\\master_ML\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\MajaE\\src\\repos\\master_ML\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\MajaE\\src\\repos\\master_ML\\.venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"c:\\Users\\MajaE\\src\\repos\\master_ML\\.venv\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\MajaE\\src\\repos\\master_ML\\.venv\\Lib\\site-packages\\keras\\src\\backend\\tensorflow\\nn.py\", line 767, in binary_crossentropy\n    raise ValueError(\nValueError: Arguments `target` and `output` must have the same rank (ndim). Received: target.shape=(None,), output.shape=(None, 39, 1)\n"}